apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: workloads
    server: https://kubernetes.default.svc
  project: workloads
  source: 
    path: templates/kafka
    repoURL: https://github.com/noelgass/cncf-lab-argocd-boostrap.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true