---
# Source: kube-prometheus/templates/alertmanager/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prometheus-alertmanager
  namespace: "default"
  labels:
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/version: 0.74.0
    helm.sh/chart: kube-prometheus-9.2.1
    app.kubernetes.io/component: alertmanager
spec:
  jobLabel: ""
  selector:
    matchLabels:
      app.kubernetes.io/component: alertmanager
  namespaceSelector:
    matchNames:
      - "default"
  endpoints:
    - port: http
      path: /metrics
